### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by devtip** [PygmySlowLoris/vue-fab#13]
Wow, this project an awesome.
Thanks for your effort! 
I have been used in my project !
Can you recommend me some learning resources?
Like Vue component, Animation?
I want to dive into.

**Comment by Edujugon** [comment]
Hi @devtip ,
Thanks for your kind words. We are glad you found useful this component.

Regarding learning resources, we recommend to read the Vue Documentation, have a deep look into open sources projects and googling those topics you are interesting on.

(I'm closing this ticket since it's not an issue)

Regards,
